// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_fr-FR/project',
  'prefix': '',
  'cacheToDisk': false,
  'lang': 'fr-FR',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_fr-FR/textnorm_swift_fr.cfg',
      'url': '',
      'md5sum': 'c3a30c4b4a60bcb85a01a65327f4efa0',
      'size': 211807,
    },
    {
      'path': '/voice_data_hmm_fr-FR/fr_number_names.far',
      'url': '',
      'md5sum': '2e8742de8d72cf817d171d4820bc5415',
      'size': 635851,
    },
    {
      'path': '/voice_data_hmm_fr-FR/phonology_fr-FR.cfg',
      'url': '',
      'md5sum': '151fcc2732b82b0e54bc7f147262b181',
      'size': 14950,
    },
    {
      'path': '/voice_data_hmm_fr-FR/fr_only.blex',
      'url': '',
      'md5sum': 'f7383e5087d3e8808073be950c5c7f73',
      'size': 2377836,
    },
    {
      'path': '/voice_data_hmm_fr-FR/phonology.pb',
      'url': '',
      'md5sum': '2ae6a9dabe8be5ef24fd7ff8d534a7a8',
      'size': 2441,
    },
    {
      'path': '/voice_data_hmm_fr-FR/g2p_m3_syls0_stress0_fr-FR.fst',
      'url': '',
      'md5sum': '4ab14f4da9d7dc7b0cd07dbc250b7673',
      'size': 476957,
    },
    {
      'path': '/voice_data_hmm_fr-FR/hmm_voice_fr_fr_vlf_medium_16000_ph_mcep_swop_ap_msd.voice',
      'url': '',
      'md5sum': '4890d4126fd56fd1ca4ae9dc663bf4a4',
      'size': 1396772,
    },
    {
      'path': '/voice_data_hmm_fr-FR/compile_hmm_16000_ph_mcep_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '4fa72329fb9204aa56ba924d72805ce5',
      'size': 7340,
    },
    {
      'path': '/voice_data_hmm_fr-FR/engine_hmm_16000_ap-server_mcep.cfg',
      'url': '',
      'md5sum': 'f972af3d50616a53a03224d964814813',
      'size': 4284,
    },
    {
      'path': '/voice_data_hmm_fr-FR/project',
      'url': '',
      'md5sum': 'd3cf25f98de0ce89a4ce8a7c6334a8b5',
      'size': 858,
    },
  ],
});
