// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_en-GB/project',
  'prefix': '',
  'cacheToDisk': false,
  'lang': 'en-GB',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_en-GB/textnorm_swift_en.cfg',
      'url': '',
      'md5sum': '3d3b92fb3314d6740d3c0230edffcb8b',
      'size': 168129,
    },
    {
      'path': '/voice_data_hmm_en-GB/en_number_names.far',
      'url': '',
      'md5sum': 'f0c36f0d374262b42e1b90a178e43704',
      'size': 607284,
    },
    {
      'path': '/voice_data_hmm_en-GB/phonology_en-GB.cfg',
      'url': '',
      'md5sum': '7058dfc5c0c86275399668cda5a85ccd',
      'size': 17481,
    },
    {
      'path': '/voice_data_hmm_en-GB/gb_only.blex',
      'url': '',
      'md5sum': 'fc43a60c2ff03ac565ece3985cd7ace9',
      'size': 524948,
    },
    {
      'path': '/voice_data_hmm_en-GB/phonology.pb',
      'url': '',
      'md5sum': 'd4fa90d031e255da7082ed4662ff2ec1',
      'size': 2137,
    },
    {
      'path': '/voice_data_hmm_en-GB/g2p_m3_syls0_stress0_en-GB.fst',
      'url': '',
      'md5sum': 'ec2ea3afdcc11c2eee9d16cafe89aae7',
      'size': 243080,
    },
    {
      'path': '/voice_data_hmm_en-GB/hmm_voice_en_gb_fis_medium_16000_ph_mcep_swop_ap_msd.voice',
      'url': '',
      'md5sum': '6419223091082925613aded383e38ef8',
      'size': 1434656,
    },
    {
      'path': '/voice_data_hmm_en-GB/compile_hmm_16000_ph_mcep_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '4fa72329fb9204aa56ba924d72805ce5',
      'size': 7340,
    },
    {
      'path': '/voice_data_hmm_en-GB/engine_hmm_16000_ap-server_mcep.cfg',
      'url': '',
      'md5sum': 'f972af3d50616a53a03224d964814813',
      'size': 4284,
    },
    {
      'path': '/voice_data_hmm_en-GB/project',
      'url': '',
      'md5sum': '33406ef7548eb356277f00dfef38b001',
      'size': 858,
    },
  ],
});
