// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_it-IT/project',
  'prefix': '',
  'cacheToDisk': false,
  'lang': 'it-IT',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_it-IT/textnorm_swift_it.cfg',
      'url': '',
      'md5sum': 'abffc6ed7607f73c51d432fae1fa8161',
      'size': 50822,
    },
    {
      'path': '/voice_data_hmm_it-IT/it_number_names.far',
      'url': '',
      'md5sum': '491e385a4a92a8995b514380c2b00be3',
      'size': 249493,
    },
    {
      'path': '/voice_data_hmm_it-IT/phonology_it-IT.cfg',
      'url': '',
      'md5sum': 'd331a0aa55d28960e3cae57c20b547e0',
      'size': 13283,
    },
    {
      'path': '/voice_data_hmm_it-IT/it_only.blex',
      'url': '',
      'md5sum': 'db1fcc88491ad84789298e13b807de42',
      'size': 2085788,
    },
    {
      'path': '/voice_data_hmm_it-IT/phonology.pb',
      'url': '',
      'md5sum': '4cfccb8b17145dd0e4ca4d2a6c537279',
      'size': 1696,
    },
    {
      'path': '/voice_data_hmm_it-IT/g2p_m3_syls0_stress0_it-IT.fst',
      'url': '',
      'md5sum': '73818b91e7c1e42ba2db67985c63e4a8',
      'size': 193783,
    },
    {
      'path': '/voice_data_hmm_it-IT/hmm_voice_it_it_kda_medium_16000_ph_mcep_swop_ap_msd.voice',
      'url': '',
      'md5sum': 'ce1276bc3f71561a9f153b18a67a586c',
      'size': 1315573,
    },
    {
      'path': '/voice_data_hmm_it-IT/compile_hmm_16000_ph_mcep_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '4fa72329fb9204aa56ba924d72805ce5',
      'size': 7340,
    },
    {
      'path': '/voice_data_hmm_it-IT/engine_hmm_16000_ap-server_mcep.cfg',
      'url': '',
      'md5sum': 'f972af3d50616a53a03224d964814813',
      'size': 4284,
    },
    {
      'path': '/voice_data_hmm_it-IT/project',
      'url': '',
      'md5sum': 'aa27c4e285065f1997c9a51ec23a7787',
      'size': 858,
    },
  ],
});
