// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_de-DE/project',
  'prefix': '',
  'cacheToDisk': false,
  'lang': 'de-DE',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_de-DE/textnorm_swift_de.cfg',
      'url': '',
      'md5sum': 'b679720582c90d81c719eccc06a23294',
      'size': 101121,
    },
    {
      'path': '/voice_data_hmm_de-DE/de_number_names.far',
      'url': '',
      'md5sum': '039c8656c61ab267020e1a8cfec49c89',
      'size': 1078501,
    },
    {
      'path': '/voice_data_hmm_de-DE/phonology_de-DE.cfg',
      'url': '',
      'md5sum': '98bd54f84e7607596036c74de3ffb49b',
      'size': 13885,
    },
    {
      'path': '/voice_data_hmm_de-DE/de_only.blex',
      'url': '',
      'md5sum': 'a05547966d8cd386fdd9bed2ad9dbb1e',
      'size': 1258896,
    },
    {
      'path': '/voice_data_hmm_de-DE/phonology.pb',
      'url': '',
      'md5sum': 'fd3e452681a31a52f001a7d374846d7c',
      'size': 2279,
    },
    {
      'path': '/voice_data_hmm_de-DE/g2p_m3_syls0_stress0_de-DE.fst',
      'url': '',
      'md5sum': '8511e6e0bccd8cc401b8232eb029977b',
      'size': 303783,
    },
    {
      'path': '/voice_data_hmm_de-DE/hmm_voice_de_de_nfh_medium_16000_ph_mcep_swop_ap_msd.voice',
      'url': '',
      'md5sum': 'e63e771f7dcba1e9efef02b1ce17175b',
      'size': 1692013,
    },
    {
      'path': '/voice_data_hmm_de-DE/compile_hmm_16000_ph_mcep_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '4fa72329fb9204aa56ba924d72805ce5',
      'size': 7340,
    },
    {
      'path': '/voice_data_hmm_de-DE/engine_hmm_16000_ap-server_mcep.cfg',
      'url': '',
      'md5sum': 'f972af3d50616a53a03224d964814813',
      'size': 4284,
    },
    {
      'path': '/voice_data_hmm_de-DE/project',
      'url': '',
      'md5sum': '06a343bedb6110b605cf3439094d1133',
      'size': 858,
    },
  ],
});
