// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_es-ES/project',
  'prefix': '',
  'cacheToDisk': false,
  'lang': 'es-ES',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_es-ES/textnorm_swift_es.cfg',
      'url': '',
      'md5sum': 'd3b2fb3da09cb80ef1f6286383f8228e',
      'size': 38514,
    },
    {
      'path': '/voice_data_hmm_es-ES/es_number_names.far',
      'url': '',
      'md5sum': 'd2aba5fab3ebeb6c363f8af9a70e6205',
      'size': 507619,
    },
    {
      'path': '/voice_data_hmm_es-ES/phonology_es-ES.cfg',
      'url': '',
      'md5sum': 'f3d2dad360fe6d12f1c0fa24e2726402',
      'size': 13379,
    },
    {
      'path': '/voice_data_hmm_es-ES/es_only.blex',
      'url': '',
      'md5sum': 'c69f223260294a0ac0c7ba4ba3868020',
      'size': 1261540,
    },
    {
      'path': '/voice_data_hmm_es-ES/phonology.pb',
      'url': '',
      'md5sum': '3927b4255ec00d5d2328c4e5845ff6c8',
      'size': 1362,
    },
    {
      'path': '/voice_data_hmm_es-ES/g2p_m3_syls0_stress0_es-ES.fst',
      'url': '',
      'md5sum': 'edef78ff6166dc0980853860d0b8364f',
      'size': 344074,
    },
    {
      'path': '/voice_data_hmm_es-ES/hmm_voice_es_es_ana_medium_16000_ph_mcep_swop_ap_msd.voice',
      'url': '',
      'md5sum': '7326b165795da5b71adaca26e04cf0f0',
      'size': 1520297,
    },
    {
      'path': '/voice_data_hmm_es-ES/compile_hmm_16000_ph_mcep_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '4fa72329fb9204aa56ba924d72805ce5',
      'size': 7340,
    },
    {
      'path': '/voice_data_hmm_es-ES/engine_hmm_16000_ap-server_mcep.cfg',
      'url': '',
      'md5sum': 'f972af3d50616a53a03224d964814813',
      'size': 4284,
    },
    {
      'path': '/voice_data_hmm_es-ES/project',
      'url': '',
      'md5sum': '3b43e721cea28fcb694928bbdeb8ed9c',
      'size': 858,
    },
  ],
});
